export type InsightBlock =
  | {
      type: "paragraph";
      text: string;
    }
  | {
      type: "heading";
      text: string;
    }
  | {
      type: "list";
      items: string[];
    }
  | {
      type: "quote";
      text: string;
    }
  | {
      type: "framework";
      items: string[];
    }
  | {
      type: "table";
      headers: string[];
      rows: string[][];
    };

export type InsightArticle = {
  slug: string;
  title: string;
  topic: string;
  company?: string;
  ticker?: string;
  published: string;
  displayDate: string;
  readingTime: number;
  abstract: string;
  content: InsightBlock[];
};

export const insightCategory = {
  slug: "insights",
  label: "Insights",
  description:
    "Short-form research notes, market observations and investment perspectives.",
};

export const insights: InsightArticle[] = [
  {
    slug: "ai-cash-returns",
    title: "The Market Is Shifting From AI Revenue Growth to AI Cash Returns",
    topic: "AI & Hyperscalers",
    published: "2026-07-27",
    displayDate: "July 27, 2026",
    readingTime: 5,
    abstract: "My current view on the hyperscaler sector is bearish.",
    content: [
      {
        type: "paragraph",
        text: "This view is not based on the assumption that AI demand will disappear. Demand for cloud infrastructure, training and inference remains strong. My concern is that the market may be underestimating how capital intensive this growth has become and how difficult it may be for hyperscalers to convert AI revenue into sustainable free cash flow.",
      },
      {
        type: "paragraph",
        text: "Alphabet is the clearest recent example, but the same risks apply to Microsoft, Amazon, Meta, Oracle and other large AI infrastructure investors.",
      },
      {
        type: "paragraph",
        text: "During the first half of 2026, Alphabet generated approximately $84.9 billion of operating cash flow but spent $80.6 billion on capital expenditures. CapEx therefore consumed about 95% of operating cash flow, compared with roughly 62% one year earlier.",
      },
      {
        type: "paragraph",
        text: "Simplified free cash flow declined from approximately $24.3 billion to $4.3 billion, a decrease of about 82%. Free cash flow margin fell to approximately 1.9%.",
      },
      {
        type: "paragraph",
        text: "The full cost of the AI infrastructure buildout may also not yet be reflected in earnings. Alphabet reported $122.8 billion of property and equipment that had not yet entered service. Cash has already been spent, but depreciation generally begins only when those assets become operational.",
      },
      {
        type: "framework",
        items: [
          "Higher AI CapEx → Lower current free cash flow",
          "New infrastructure entering service → Higher depreciation and operating costs",
        ],
      },
      {
        type: "paragraph",
        text: "Google Cloud remains strong, with second-quarter revenue growth of approximately 82% and operating margin of around 35.6%. The concern is not that Cloud profitability has already weakened. The question is whether current growth and margins can be sustained once the full cost of newer AI infrastructure is recognized.",
      },
      {
        type: "heading",
        text: "Six Metrics I Am Watching",
      },
      {
        type: "table",
        headers: ["Metric", "Alphabet example", "Bearish signal"],
        rows: [
          [
            "CapEx / operating cash flow",
            "95%",
            "Remains near or above 100%",
          ],
          [
            "Free cash flow",
            "$4.3B, down 82%",
            "Cloud grows but FCF stays weak",
          ],
          [
            "FCF margin",
            "1.9%",
            "Cash conversion continues to decline",
          ],
          [
            "Assets not yet in service",
            "$122.8B",
            "Depreciation rises faster than Cloud profit",
          ],
          [
            "Net debt issuance / CapEx",
            "63%",
            "Borrowing rises while FCF remains weak",
          ],
          [
            "EBIT / interest expense",
            "44.4x",
            "Interest expense grows faster than EBIT",
          ],
        ],
      },
      {
        type: "paragraph",
        text: "The final test is incremental ROIC relative to WACC. AI investment creates value only when the additional operating profit and cash flow generated by new infrastructure exceed the company’s cost of capital.",
      },
      {
        type: "paragraph",
        text: "Alphabet is not facing a debt crisis. Its interest coverage remains strong and it retains substantial liquidity. However, the direction of change matters. Total debt more than doubled during the first half of 2026, net debt issuance reached approximately $51 billion and interest expense increased by more than 500%.",
      },
      {
        type: "paragraph",
        text: "The macro environment adds further pressure. Near-term Federal Reserve tightening expectations have risen, the 10-year Treasury yield is around 4.7%, and the 10-year real yield is around 2.4%.",
      },
      {
        type: "paragraph",
        text: "Higher rates affect hyperscalers in two ways:",
      },
      {
        type: "framework",
        items: [
          "Higher rates → Higher financing costs",
          "Higher WACC → Lower present value of long-duration AI cash flows",
        ],
      },
      {
        type: "paragraph",
        text: "Market risk indicators have also deteriorated. The VIX is around 19, bearish investor sentiment is above 40%, and index put volume has exceeded call volume. These conditions do not indicate a systemic crisis, but they suggest that investors are becoming less willing to tolerate uncertain returns, falling free cash flow and aggressive capital spending.",
      },
      {
        type: "heading",
        text: "Investment View",
      },
      {
        type: "paragraph",
        text: "My bearish view applies to the hyperscaler sector as a whole.",
      },
      {
        type: "paragraph",
        text: "The sector currently faces three pressures:",
      },
      {
        type: "framework",
        items: [
          "Higher rates → Higher WACC → Lower valuation multiples",
          "Higher AI CapEx → Lower near-term free cash flow",
          "Future infrastructure deployment → Higher depreciation and operating costs",
        ],
      },
      {
        type: "paragraph",
        text: "The central question is no longer whether AI demand is growing. It is whether hyperscalers can generate enough incremental operating profit and free cash flow to justify the scale and cost of their AI investment.",
      },
      {
        type: "paragraph",
        text: "Until operating cash flow begins to grow faster than CapEx and there is clearer evidence that incremental AI ROIC exceeds WACC, I believe the risk-reward profile for hyperscalers remains skewed to the downside.",
      },
    ],
  },
];

export function sortedInsights() {
  return [...insights].sort((a, b) =>
    b.published.localeCompare(a.published),
  );
}

export function insightBySlug(slug: string) {
  return insights.find((insight) => insight.slug === slug);
}
