export type CategorySlug =
  | "equity-research"
  | "investment-reports"
  | "economic-analysis";

export type ResearchReport = {
  slug: string;
  category: CategorySlug;
  categoryLabel: string;
  title: string;
  company?: string;
  ticker?: string;
  published: string;
  displayDate: string;
  pages: number;
  abstract: string;
  takeaways: string[];
  pdf: string;
  featured: boolean;
};

export const categories: {
  slug: CategorySlug;
  label: string;
  description: string;
}[] = [
  {
    slug: "equity-research",
    label: "Equity Research",
    description:
      "Fundamental company research, earnings analysis and valuation.",
  },
  {
    slug: "investment-reports",
    label: "Investment Reports",
    description:
      "Focused investment theses, portfolio perspectives and scenario work.",
  },
  {
    slug: "economic-analysis",
    label: "Economic Analysis",
    description:
      "Independent analysis of macroeconomic trends and capital markets.",
  },
];

export const reports: ResearchReport[] = [
  {
    slug: "memory-cycle-price-led-rollover",
    category: "equity-research",
    categoryLabel: "Equity Research",
    title: "Memory Cycle at an Inflection Point",
    company: "Micron · SK hynix · Samsung Electronics",
    published: "2026-08-10",
    displayDate: "August 10, 2026",
    pages: 11,
    abstract:
      "The proprietary Memory Cycle Tracker places Micron, SK hynix and Samsung Electronics in Stage 10—Price-Led Roll-Over. Forward EBITDA estimates are still rising, but revision momentum has deteriorated sharply and all three stocks have turned lower. The synchronized signal marks a late-cycle inflection point rather than a confirmed earnings downturn.",
    takeaways: [
      "All three companies have positive three-month EBITDA revisions, deeply negative revision acceleration and negative three-month stock returns.",
      "SK hynix shows the most advanced deterioration, while Micron retains the strongest revision profile and Samsung offers greater business diversification.",
      "Low forward EV/EBITDA multiples may reflect peak-cycle earnings rather than a durable valuation floor.",
    ],
    pdf: "/reports/memory_cycle_at_an_inflection_point.pdf",
    featured: false,
  },
  {
    slug: "us-late-cycle-slowdown-august-2026",
    category: "economic-analysis",
    categoryLabel: "Economic Analysis",
    title: "The Fed’s New Problem: Weak Jobs Without Low Inflation",
    published: "2026-08-07",
    displayDate: "August 7, 2026",
    pages: 17,
    abstract:
      "The July employment report revealed a harder policy problem than the growth scare of August 2024. Payroll growth is now near stall speed and participation has weakened, yet inflation remains above target while private demand, manufacturing and credit conditions are still resilient. The economy is not in recession, but the Federal Reserve has no simple response to weak hiring without low inflation.",
    takeaways: [
      "Unlike August 2024, three-month average payroll growth is now near 20,000 while core PCE inflation remains above 3%.",
      "Manufacturing, services, private domestic demand and credit conditions still argue against an immediate recession call.",
      "The main risk is a policy dilemma: tightening could worsen employment, while aggressive easing could reignite inflation.",
    ],
    pdf: "/reports/us_late_cycle_slowdown_august_2026.pdf",
    featured: false,
  },
  {
    slug: "ai-capex-cycle-cash-return-phase",
    category: "equity-research",
    categoryLabel: "Equity Research",
    title: "The AI CapEx Cycle Is Entering Its Cash-Return Phase",
    published: "2026-08-03",
    displayDate: "August 3, 2026",
    pages: 15,
    abstract:
      "The AI infrastructure cycle is entering a more demanding stage. The next phase will be defined less by how much capital is deployed and more by whether those assets can generate sufficient utilization, revenue and cash returns. The central investment question is whether AI-related revenue and cash contribution can grow faster than depreciation, infrastructure operating costs and replacement investment.",
    takeaways: [
      "The AI infrastructure cycle is transitioning from a buildout story into a return-on-capital story.",
      "CapEx is the upfront cash-flow burden, while depreciation is the delayed earnings burden.",
      "The main risk is that the overall cost base compounds faster than the economic returns generated by the infrastructure.",
    ],
    pdf: "/reports/ai_capex_cycle_cash_return_phase.pdf",
    featured: true,
  },
  {
    slug: "alphabet-q2-2026",
    category: "equity-research",
    categoryLabel: "Equity Research",
    title:
      "Search Resilience, Cloud Acceleration and the Economics of the AI Infrastructure Build-out",
    company: "Alphabet Inc.",
    ticker: "GOOG / GOOGL",
    published: "2026-07-26",
    displayDate: "July 26, 2026",
    pages: 185,
    abstract:
      "This report evaluates Alphabet’s Q2 2026 results across Search, YouTube, Google Cloud, AI monetization, infrastructure spending and valuation. Google Cloud was the quarter’s strongest operating contributor, while Search remained resilient as AI-powered products increased engagement. These positives were offset by sharply higher capital expenditures, negative quarterly free cash flow and rising infrastructure-related costs. The analysis separates recurring operating performance from material non-operating investment gains and develops normalized earnings, EBITDA, free-cash-flow and sum-of-the-parts valuations.",
    takeaways: [
      "Google Cloud was the highest-quality component of the quarter, with 81.8% revenue growth and a 35.6% operating margin.",
      "Search remained resilient, but long-term AI economics depend on monetization exceeding inference and infrastructure costs.",
      "Elevated capital expenditure and negative near-term free cash flow remain the principal valuation risks.",
    ],
    pdf: "/reports/alphabet_full_equity_research_report_q2_2026.pdf",
    featured: false,
  },
  {
    slug: "economic-cycle-framework",
    category: "economic-analysis",
    categoryLabel: "Economic Analysis",
    title:
      "Economic Cycle Framework: Five-Dimension Assessment, Market Performance, and Late-Cycle Pathways",
    published: "2026-07-29",
    displayDate: "July 29, 2026",
    pages: 31,
    abstract:
      "This report presents a five-dimension framework for assessing the economic cycle through growth, employment, inflation, financial conditions and credit. It defines practical thresholds for eight macroeconomic regimes, maps each regime to expected equity-market behavior, and outlines the decision rules and transmission mechanisms behind soft-landing, stagflation and hard-landing pathways.",
    takeaways: [
      "Economic regimes should be assessed through direction, duration and confirmation across all five dimensions rather than through isolated data points.",
      "The late-cycle path depends primarily on whether inflation continues to decline and whether employment and credit remain stable.",
      "Equity-market leadership, rate sensitivity and the relative performance of growth and defensive sectors vary systematically across the economic cycle.",
    ],
    pdf: "/reports/economic_cycle_framework.pdf",
    featured: false,
  },
];

export function reportsForCategory(category: CategorySlug) {
  return reports
    .filter((report) => report.category === category)
    .sort((a, b) => b.published.localeCompare(a.published));
}
